### PR TITLE
Save without index

### PR DESCRIPTION
**Pull request by ynqa**
### Overview

- Save without index:
  - before: `<word> <index1>:<value1> <index2>:<value2> ...`
  - after: `<word> <value1> <value2> ...`

### CODE REVIEW

**Comment by chewxy** [comment]
Is the reason for this smaller binary files?

**Comment by ynqa** [comment]
Simply set the format the same as original word2vec output. I also thought the indexes of word vector are unnecessary info.

**Comment by chewxy** [comment]
This way you can just use Gorgonia's serialization methods and dump them

**Comment by ynqa** [comment]
Right, so does it resolves the issue #9?

**Pull request merged**
