### PR TITLE
Change package to gorgonia.org/tensor

### PR DESCRIPTION
**Pull request by ynqa**
### Overview

- Change package: `github.com/chewxy/gorgonia/tensor` to `gorgonia.org/tensor`.
- Change glide to dep.

### CODE REVIEW

**Comment by chewxy** [comment]
dammit, I thought I solved that stupid vendoring problem. Gimme 30 mins

**Comment by chewxy** [comment]
Aha... the import URL is wrong.


It's `import "gorgonia.org/tensor"`

**Comment by ynqa** [comment]
Sure 👍

**Comment by chewxy** [comment]
lgtm

**Pull request merged**
